task 3
js-tasks-ru/js-20220111_mivanova pull request #3
Opened 2022-01-20 17:03 UTC by ivanovamar

task 3

2022-01-20 17:04 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-20 23:31 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      let pathArr = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2022-01-20 23:31 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      let pathArr = path.split('.');
`pathArr` - это `const`

2022-01-20 23:32 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (let key in obj) {
`key` - это `const`
Помните какой недостаток есть у `for...in` цикла?

2022-01-20 23:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      for (let i = 0; i < pathArr.length; i++) {
почему бы не заменить `for` на `for...of` цикл?
это позволит избавиться от проверки `pathArr.length` и от инкрементирования `let`

2022-01-20 23:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  let count = 1;
👍 good

2022-01-20 23:34 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    for (let key in obj) {
может `key` это `const`?
не забывайте про недостаток `for...in` цикла - он итерирует как по собственным так и по унаследованным свойствам объекта

2022-01-20 23:35 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  if (arr){
👍 good
но есть более короткое решение:
```
return [...new Set(arr)]
```

2022-01-20 23:35 UTC, dosandk requested changes
решение `createGetter` следует поправить

2022-01-21 07:29 UTC, ivanovamar commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      for (let i = 0; i < pathArr.length; i++) {
да, я помню про цикл for... in, но использовала его по примеру задачи Проверка на пустоту в учебнике
сейчас переделаю на for...of

2022-01-21 07:30 UTC, ivanovamar commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    for (let key in obj) {
key - это const, поняла) 
как обычно, копипастом разнесла один косяк по всем задачам

2022-01-21 07:34 UTC, ivanovamar commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      for (let i = 0; i < pathArr.length; i++) {
правда, когда заменяешь цикл, то ломается вообще вся логика решения(

2022-01-21 11:07 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-21 11:08 UTC, ivanovamar commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      let pathArr = path.split('.');
Первую задачу поправила

2022-01-21 15:51 UTC, dosandk approved these changes
good 👍

2022-01-21 15:51 UTC, merged